### ISSUE TITLE
[libchardet] Improper UTF-8 detection of some files (regression?)

### ISSUE THREAD

**Issue by RamonUnch** [roytam1/rtoss#7]
Try with this random gibberish I typed in Windows-1252

[notU8.txt](https://github.com/roytam1/rtoss/files/11798516/notU8.txt)

It is now auto-detected as UTF-8 by the latest chardet.dll (when I build it myself or I take it from your latest GreenPad-1.08.3 build).
However it contains invalid sequences:

Actually just this sequence is detected as UTF-8:
`é"èr` in cp1252 ie: `E9 22 E8 72` which is an invalid sequence. `E9` defines a 3 byte sequence so the following byte should be of the form `10xxxxxx` also E8 cannot be there.

Maybe some invalid sequences could be tolerated but they should be a minority.

If I use an older chardet.dll version I do not have the problem.

**Comment by roytam1** [comment]
yeah it should be something wrong from upstream chardet updates (https://github.com/Joungkyun/libchardet)

**Comment by RamonUnch** [comment]
> yeah it should be something wrong from upstream chardet updates (https://github.com/Joungkyun/libchardet)

I just build the upstreal 1.0.6 release and I got no false positive (for this file) there.

**Comment by RamonUnch** [comment]
Whops ignore the above my test was invalid, the export table is different and the dll could not be loaded properly.

**Comment by RamonUnch** [comment]
Well this commit seems to be culprit https://github.com/roytam1/rtoss/commit/c83f96dbb80707c2f85cd272fd33bcd43e827014
increasing the `float unlike = 0.5f;` to `float unlike = 0.66f` or more fixes it for me, it was 0.99 before, also maybe `ONE_CHAR_PROB` could be changed instead.

This commit increases false positives in some cases for sure.
